# Generated by Django 4.2.27 on 2026-03-15 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cio',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='cio',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='CIOMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('cio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.cio')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.profile')),
            ],
            options={
                'unique_together': {('profile', 'cio')},
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='cios',
            field=models.ManyToManyField(blank=True, related_name='profiles', through='core.CIOMembership', to='core.cio'),
        ),
    ]
