# Generated by Django 4.2.27 on 2026-03-25 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_cio_created_by_alter_cio_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "cio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.cio"
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.profile"
                    ),
                ),
            ],
            options={
                "unique_together": {("profile", "cio")},
            },
        ),
    ]
