# Generated by Django 4.2.27 on 2026-03-25 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_review"),
        ("core", "0004_uploadedfile"),
    ]

    operations = []
