# Generated by Django 4.2.27 on 2026-03-28 06:43

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_0004_review_0004_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to=core.models.cio_upload_path),
        ),
    ]
