# Generated by Django 4.2.27 on 2026-04-06 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_dm_conversation_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="profile_pictures/defaultPic.jpg",
                upload_to="profile_pictures",
            ),
        ),
    ]
