# Generated by Django 4.2.27 on 2026-04-06 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_profile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                default="profile_pictures/defaultPic.jpg", upload_to="profile_pictures"
            ),
        ),
    ]
