# Generated by Django 4.2.27 on 2026-04-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('exec', 'CIO Exec Member'), ('student', 'UVA Student'), ('guest', 'Guest'), ('user_admin', 'User Administrator')], default='guest', max_length=20),
        ),
    ]
