# Generated by Django 4.2.27 on 2026-04-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_profile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="cio",
            name="cio_profile_picture",
            field=models.ImageField(
                default="cio_profile_pictures/CioDefaultProfilePic.png",
                upload_to="cio_profile_pictures",
            ),
            preserve_default=False,
        ),
    ]
