# Generated by Django 4.2.27 on 2026-04-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_cio_cio_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='cio',
            name='avg_career_development',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cio',
            name='avg_community_inclusiveness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cio',
            name='avg_event_quality',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cio',
            name='avg_time_commitment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='rating_career_development',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='rating_community_inclusiveness',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='rating_event_quality',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='rating_time_commitment',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
    ]
