# Generated by Django 4.2.27 on 2026-04-18 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_review_anonymous'),
    ]

    operations = [
        migrations.CreateModel(
            name='CIOLeadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('cio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderships', to='core.cio')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderships', to='core.profile')),
            ],
            options={
                'unique_together': {('profile', 'cio')},
            },
        ),
        migrations.DeleteModel(
            name='CIOMembership',
        ),
        migrations.AlterField(
            model_name='profile',
            name='cios',
            field=models.ManyToManyField(blank=True, related_name='profiles', through='core.CIOLeadership', to='core.cio'),
        ),
    ]
