# Generated by Django 4.2.27 on 2026-04-18 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_cioleadership_delete_ciomembership_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'UVA Student'), ('guest', 'Guest'), ('user_admin', 'User Administrator')], default='guest', max_length=20),
        ),
    ]
