# Generated by Django 4.2.27 on 2026-04-18 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_profile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CIOMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('cio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.cio')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.profile')),
            ],
            options={
                'unique_together': {('profile', 'cio')},
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='member_cios',
            field=models.ManyToManyField(blank=True, related_name='member_profiles', through='core.CIOMembership', to='core.cio'),
        ),
    ]
