# Generated by Django 4.2.27 on 2026-04-18 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_ciomembership_profile_member_cios'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_requests', to='core.cio')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_requests', to='core.profile')),
            ],
            options={
                'unique_together': {('profile', 'cio')},
            },
        ),
    ]
