# Generated by Django 4.2.27 on 2026-04-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_comment_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='year',
            field=models.IntegerField(blank=True, choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')], help_text="Reviewer's year at the time of the review (optional).", null=True),
        ),
    ]
