# Generated by Django 4.2.27 on 2026-04-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_review_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('color', models.CharField(default='#2a6fb5', help_text="Hex color used for this category's badge (e.g. #4a8fd4).", max_length=7)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='cio',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Optional categories/tags describing this CIO.', related_name='cios', to='core.category'),
        ),
    ]
